model: 'fnn_ao' # 'base' 'fuzzy_tree' 'fuzzy_tree_fn' 'fnn_ao'

n_run: 1
n_kfolds: 3

n_agents: 5
n_agents_list: []

n_rules: 3
n_rules_list: []

dataset_list:
  ['eegDual_subj1', 'eegDual_subj2', 'eegDual_subj3', 'eegDual_subj4', 'eegDual_subj5',
  'eegDual_subj6', 'eegDual_subj7', 'eegDual_subj8', 'eegDual_subj9', 'eegDual_subj10',
  'eegDual_subj11']
dataset_list_all:
  ['abalone', 'airfoil', 'bikesharing',
   'blog', 'bodyfat', 'CASP', 'CCPP', 'eegDual_sub1',
   'housing', 'HRSS_anomalous_optimized', 'HRSS_anomalous_standard',
   'kc_house', 'motor_temperature', 'quake', 'skills',
   'statlib_calhousing', 'strength', 'telemonitoring', 'yacht']

mu_current: 0.001
mu_list:
  [0.0001, 0.001, 0.01, 0.1]

rho: 1

#tool functions
h_computer: 'normal' # 'base' 'normal'
fnn_solver: 'normal' # 'base' 'normal' 'sigmoid'
loss_fun: 'likely'  # 'base' 'rmse' 'nrmse' 'mse' 'map' 'likely'
rules: 'kmeans' # 'kmeans' 'fuzzyc'
patition_strategy: 'kmeans'

#feature splitor
feature_seperator: 'slice_window' # 'slice_window' 'random_pick' 'no_seperate'
window_size: 4 # 4 bands
n_level: 2
# while feature_seperator is slice_window, initiate following parameters
step: 4
# while feature_seperator is random_pick, initiate following parameters
n_repeat_select: 30

# rule number tree
tree_rule_spesify: 'true' # 'false' 'true'
n_rule_pos: [2, 0] # 0 stands for all, number(1...5) denotes for index
n_rule_spesify: 1


#logger
log_to_file: 'false' # 'false' 'true'